namespace CerealREST.Models
{
    public class CerealFilter
    {
        public string? Name { get; set; }
        public string? Mfr { get; set; }
        public string? Type { get; set; }

        public int? Calories { get; set; }
        public int? CaloriesGT { get; set; }
        public int? CaloriesLT { get; set; }
        public int? CaloriesGTE { get; set; }
        public int? CaloriesLTE { get; set; }
        public int? CaloriesNot { get; set; }
        public int? Protein { get; set; }
        public int? ProteinGT { get; set; }
        public int? ProteinLT { get; set; }
        public int? ProteinGTE { get; set; }
        public int? ProteinLTE { get; set; }
        public int? ProteinNot { get; set; }
        public int? Fat { get; set; }
        public int? FatGT { get; set; }
        public int? FatLT { get; set; }
        public int? FatGTE { get; set; }
        public int? FatLTE { get; set; }
        public int? FatNot { get; set; }
        public int? Sodium { get; set; }
        public int? SodiumGT { get; set; }
        public int? SodiumLT { get; set; }
        public int? SodiumGTE { get; set; }
        public int? SodiumLTE { get; set; }
        public int? SodiumNot { get; set; }
        public double? Fiber { get; set; }
        public double? FiberGT { get; set; }
        public double? FiberLT { get; set; }
        public double? FiberGTE { get; set; }
        public double? FiberLTE { get; set; }
        public double? FiberNot { get; set; }
        public double? Carbo { get; set; }
        public double? CarboGT { get; set; }
        public double? CarboLT { get; set; }
        public double? CarboGTE { get; set; }
        public double? CarboLTE { get; set; }
        public double? CarboNot { get; set; }
        public int? Sugars { get; set; }
        public int? SugarsGT { get; set; }
        public int? SugarsLT { get; set; }
        public int? SugarsGTE { get; set; }
        public int? SugarsLTE { get; set; }
        public int? SugarsNot { get; set; }
        public int? Potass { get; set; }
        public int? PotassGT { get; set; }
        public int? PotassLT { get; set; }
        public int? PotassGTE { get; set; }
        public int? PotassLTE { get; set; }
        public int? PotassNot { get; set; }
        public int? Vitamins { get; set; }
        public int? VitaminsGT { get; set; }
        public int? VitaminsLT { get; set; }
        public int? VitaminsGTE { get; set; }
        public int? VitaminsLTE { get; set; }
        public int? VitaminsNot { get; set; }
        public int? Shelf { get; set; }
        public int? ShelfGT { get; set; }
        public int? ShelfLT { get; set; }
        public int? ShelfGTE { get; set; }
        public int? ShelfLTE { get; set; }
        public int? ShelfNot { get; set; }
        public double? Weight { get; set; }
        public double? WeightGT { get; set; }
        public double? WeightLT { get; set; }
        public double? WeightGTE { get; set; }
        public double? WeightLTE { get; set; }
        public double? WeightNot { get; set; }
        public double? Cups { get; set; }
        public double? CupsGT { get; set; }
        public double? CupsLT { get; set; }
        public double? CupsGTE { get; set; }
        public double? CupsLTE { get; set; }
        public double? CupsNot { get; set; }
        public double? Rating { get; set; }
        public double? RatingGT { get; set; }
        public double? RatingLT { get; set; }
        public double? RatingGTE { get; set; }
        public double? RatingLTE { get; set; }
        public double? RatingNot { get; set; }
    }
}
